//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveFixForWuxia.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveFixForWuxia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 100933=熊胆
        ///110001=逍遥散
        ///110002=再造膏
        ///110003=承气散
        ///110004=黑玉断续膏
        ///110005=天香断续胶
        ///110006=九转还魂丹
        ///110007=双冲饮
        ///110008=三黄宝腊丹
        ///110009=青龙散
        ///110010=茯苓首乌丸
        ///110011=田七鲨胆散
        ///110012=九花玉露丸
        ///110013=十全大补丹
        ///110014=牛黄血竭丹
        ///110015=通犀地龙丸
        ///110016=胭脂泪
        ///110017=千锤百炼丹
        ///110018=飘飘丸
        ///110019=洗髓再造丹
        ///110020=神恩通慧丹
        ///110021=千年人参
        ///110022=大王蛇胆
        ///110023=朱蛤
        ///110024=玉蜂浆
        ///110025=怪鲶鱼
        ///110027=回阳五龙膏
        ///110028=三顺散
        ///110031=腊八粥
        ///110032=神鱼
        ///110033=老鼠肉
        ///110034=玄冰烈火酒
        ///110035=黑蚂蚁升精丸
        ///110036=西湖醋鱼
        ///110037=道口烧鸡
        ///110038=龙井虾仁
        ///110039=叫化子鸡
        ///110040=东坡肉
        ///110041=开水白菜
        ///110042= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string itemlist {
            get {
                return ResourceManager.GetString("itemlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon MainICo {
            get {
                object obj = ResourceManager.GetObject("MainICo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 60001=逍遥雁行式 60002=小无相功
        ///60003=逍遥鹏飞式 60004=大湿婆密咒
        ///60005=日月神功 60006=侠隐诀
        ///60007=心合意气流 60008=冰火玄功
        ///60009=龙腾豹变 60010=天罡功
        ///60011=八卦心法 60012=千仞诀
        ///60013=毒龙功 60014=七弦神功
        ///60015=武当九阳神功 60016=武当九阳玄功
        ///60017=降魔功 60018=神剑诀
        ///60019=天山心法 60020=少林九阳功
        ///60021=峨嵋九阳功 60022=霹雳心法
        ///60023=金风心法 60024=清心普散咒
        ///60025=五毒心经 60026=兽王功
        ///60027=九纹龙啸功 60028=忘忧心法
        ///60029=太易星辰诀 60030=万物皆数
        ///60031=飞燕功 60032=隐元韬晦诀
        ///60033=无涯古圣功 60034=清心诀
        ///60035=紫霞神功 60036=血刀经
        ///60037=野拳神功 60038=莲花经
        ///60039=金刚不坏体 60040=罗汉降魔功
        ///60041=修罗心法 60042=华陀医典
        ///60043=道生一 60044=玉女心法
        ///6 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string neigong {
            get {
                return ResourceManager.GetString("neigong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100008=凌香儿
        ///100017=无瑕子
        ///100019=老胡
        ///100026=醉仙
        ///100027=橘叟
        ///100028=神医
        ///100029=仙音
        ///100030=书生
        ///100031=丹青
        ///100033=沈澜
        ///100037=方云华
        ///100054=任清璇
        ///100056=纪玟
        ///100058=蓝婷
        ///100059=史燕
        ///100061=风吹雪
        ///100065=史刚
        ///100066=史义
        ///100072=西门峰
        ///100075=江瑜
        ///100078=关伟
        ///100081=唐冠南
        ///100082=唐中慧
        ///100085=夏侯非
        ///100089=商仲仁
        ///100091=杨云
        ///100096=巩光杰
        ///100135=徐子骐
        ///100297=陆少临
        ///100299=燕宇
        ///100419=花痴
        ///200000=卫紫绫
        ///200001=韦子陵
        ///200016=水盼盼
        ///200017=龙墨
        ///200020=萧复
        ///200022=塔娅
        ///200027=敖广
        ///200038=不动
        ///200039=岳胖子
        ///200040=岳晓遥
        ///200044=楚绘
        ///210001=谷月轩
        ///210002=荆棘
        ///210003=沈湘 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NPClist {
            get {
                return ResourceManager.GetString("NPClist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 200=讨价还价。能以较低的价格买入道具
        ///201=无奸不商。能以较高的价格卖出道具
        ///202=明察秋毫。容易发现场景上的隐藏物品
        ///203=潜龙蝶影。敌人警戒的距离降低
        ///204=大收藏家。可以看见商店隐藏的物品
        ///205=喜从天降。战斗掉宝的机率增加
        ///206=天生神童。平时可以帮助全队获得更多的经验
        ///207=见多识广。平时可以帮助全队获得更多的阅历
        ///208=神农百草。容易发现场景上的草药
        ///209=矿石冶炼。容易发现场景上的矿石
        ///210=毒物探索。容易发现场景上的毒虫
        ///301=兄弟情深。每有一名队友伤重离场时，获得霸体，下次攻击必定暴击
        ///302=血战到底。第一次伤重离场时，以意志力残存，继续再战
        ///303=隐匿。休息后进入隐匿状态，隐匿状态下攻击必定暴击
        ///304=遗策点穴。伤重离场时，周遭二格敌人下回合不能行动
        ///305=妙手空空。攻击时有概率偷得敌人身上物品，目标血量越低，成功概率越大
        ///306=有事先走。血量低于15%必定离场
        ///307=国色天香。周遭二格男性角色伤害提升
        ///308=我佛慈悲。攻击后不会造成对方伤重离场，必定留下一条生路
        ///309=背刺。从背后攻击，必定暴击
        ///310=逆 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Talent {
            get {
                return ResourceManager.GetString("Talent", resourceCulture);
            }
        }
    }
}
